<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Mir-PC" ignored="0" name="Test(failed)(failed)" tests="3" failures="1" timestamp="23 Sep 2020 06:14:33 GMT" time="85.905" errors="0">
  <testcase name="verifyLoginPageText" time="1.781" classname="retry_FinalTests.TestNGExampleTests">
    <skipped/>
  </testcase> <!-- verifyLoginPageText -->
  <testcase name="verifyLoginPageText" time="5.127" classname="retry_FinalTests.TestNGExampleTests">
    <failure type="java.lang.AssertionError" message="Forced to fail">
      <![CDATA[java.lang.AssertionError: Forced to fail
at retry_FinalTests.TestNGExampleTests.verifyLoginPageText(TestNGExampleTests.java:46)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginPageText -->
  <testcase name="verifyForgotPasswordPage" time="11.195" classname="retry_FinalTests.TestNGExampleTests"/>
</testsuite> <!-- Test(failed)(failed) -->
